In [1]:
import pandas as pd

ModuleNotFoundError: No module named 'pandas'

In [2]:
import tensorflow as tf

In [3]:
import tensorflow as tf
print(tf.config.list_physical_devices('GPU'))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [2]:
data = pd.read_csv('dataset-string-similarity.txt', sep='\t', header=None)

In [3]:
data.head()

,0,1,2,3,4,5,6,7,8
0,la dom nxy,ลำโดมน้อย,True,1610905,1610905,LATIN,THAI,TH,TH
1,Sharunyata,Shartjugskij,False,495626,495628,LATIN,LATIN,RU,RU
2,Krutoy,Крутой,True,1501675,1501675,LATIN,CYRILLIC,RU,RU
3,Sutangcun,羊山村,False,1552807,1552810,LATIN,CJK,CN,CN
4,Jowkār-e Shafī‘,جوکار شفیع,True,43454,43454,LATIN,ARABIC,IR,IR

In [4]:
data.columns = ['name_1', 'name_2', 'match', 'id_1', 'id_2', 'alphabet_1', 'alphabet_2', 'language_1', 'language_2']

In [5]:
df_latin_pairs = data[(data.alphabet_1 == 'LATIN') & (data.alphabet_2 == 'LATIN')].dropna()

In [6]:
df_latin_pairs.groupby('match').count()

,name_1,name_2,id_1,id_2,alphabet_1,alphabet_2,language_1,language_2
match,,,,,,,,
False,1765238,1765238,1765238,1765238,1765238,1765238,1765238,1765238
True,1554133,1554133,1554133,1554133,1554133,1554133,1554133,1554133

In [7]:
df_latin_pairs

,name_1,name_2,match,id_1,id_2,alphabet_1,alphabet_2,language_1,language_2
1,Sharunyata,Shartjugskij,False,495626,495628,LATIN,LATIN,RU,RU
5,rongreiyn ban hwy h wk cxmthxng,rongreiyn ban hnxng xu,False,8459620,8459621,LATIN,LATIN,TH,TH
7,Engeskjæran,Abrahamskjeret,False,9719134,9719147,LATIN,LATIN,NO,NO
8,Izumo-zaki,Tsumo-zaki,True,1861080,1861080,LATIN,LATIN,JP,JP
10,Qermez Khalifeh-ye `Olya,Qermez Khalīfeh-ye ‘Olyā,True,1259,1259,LATIN,LATIN,IR,IR
...,...,...,...,...,...,...,...,...,...
4999995,Salhon,La Salencon Rivière,False,2976476,2976479,LATIN,LATIN,FR,FR
4999996,Abḏul,Sēyyed Gholām `Abd ol,True,1126224,1126224,LATIN,LATIN,AF,AF
4999997,aibrahym abad,aabramabad,False,135502,135503,LATIN,LATIN,IR,IR
4999998,jiu yuan gou cun,Jiuyuan Goucun,True,11116942,11116942,LATIN,LATIN,CN,CN
4999999,Assaisse,Assaki (CR),False,6546482,6546483,LATIN,LATIN,MA,MA

In [8]:
from Levenshtein import jaro_winkler

In [9]:
jaro_winkler('home', 'home 2')

0.9333333333333333

In [10]:
df_latin_pairs['jaro_winkler'] = df_latin_pairs.apply(lambda row: jaro_winkler(row['name_1'], row['name_2']), axis=1)

In [11]:
df_latin_pairs_filtered = df_latin_pairs[df_latin_pairs['jaro_winkler']>.75]

In [12]:
df_latin_pairs_filtered.groupby('match').count()

,name_1,name_2,id_1,id_2,alphabet_1,alphabet_2,language_1,language_2,jaro_winkler
match,,,,,,,,,
False,344126,344126,344126,344126,344126,344126,344126,344126,344126
True,1012572,1012572,1012572,1012572,1012572,1012572,1012572,1012572,1012572

In [13]:
df_latin_pairs_filtered[df_latin_pairs_filtered['language_1']=='ES'][:50]

,name_1,name_2,match,id_1,id_2,alphabet_1,alphabet_2,language_1,language_2,jaro_winkler
40,Caserio El Bobar,Caserío El Bobar,True,2518689,2518689,LATIN,LATIN,ES,ES,0.975000
418,Sierra de Los Rios,Sierra de los dos Rios,True,3123802,3123802,LATIN,LATIN,ES,ES,0.919905
1496,Cerébanes,Serébanes,True,3125394,3125394,LATIN,LATIN,ES,ES,0.925926
1890,Vilaestévez,Villateves,True,3105636,3105636,LATIN,LATIN,ES,ES,0.882391
3693,Arnego,Arnedo,False,3129473,3129476,LATIN,LATIN,ES,ES,0.933333
5244,Castrillo Matajudíos,Castrillo Mota de Judíos,True,3125725,3125725,LATIN,LATIN,ES,ES,0.907778
6168,Sant Llorenç des Cardassar,Sant Llorenc del Cardassar,True,2511309,2511309,LATIN,LATIN,ES,ES,0.944231
6819,Caserío Las Rosuelas,Caserio Las Quebradas,False,2515235,2515247,LATIN,LATIN,ES,ES,0.866190
7444,Teberga,Teverga,True,3119220,3119220,LATIN,LATIN,ES,ES,0.923810
7540,Villardevos,Villardevós,True,3105004,3105004,LATIN,LATIN,ES,ES,0.963636
7974,Sierra Mariánica,Cordillera Mariánica,True,2513552,2513552,LATIN,LATIN,ES,ES,0.873611
9042,Las Maravillas,Barrio Las Maravillas,True,2515325,2515325,LATIN,LATIN,ES,ES,0.769841
10946,Salmerón,Salmeron,True,2511516,2511516,LATIN,LATIN,ES,ES,0.950000
11806,Canadas,Cañadas,True,2520343,2520343,LATIN,LATIN,ES,ES,0.923810
12192,Santibazez,Santibáñez de Valdeiglesias,True,3109592,3109592,LATIN,LATIN,ES,ES,0.824444
12665,Caserio La Juaida,Caserío La Jayona,False,2515839,2515843,LATIN,LATIN,ES,ES,0.905882
14054,tarankwn,Tarankon,True,3108317,3108317,LATIN,LATIN,ES,ES,0.833333
16522,Caserío La Masada,Caserio La Masada,True,3119464,3119464,LATIN,LATIN,ES,ES,0.976471
16540,San Martin,San Martín,True,3113434,3113434,LATIN,LATIN,ES,ES,0.960000
16561,Buenavista,Buenache,False,2520771,2520775,LATIN,LATIN,ES,ES,0.825000
17234,Monte de Espiñeira,Monte Tabeirós,True,3108451,3108451,LATIN,LATIN,ES,ES,0.833968
19836,Masía de Les Candeales,Caserío Les Candeales,True,3118501,3118501,LATIN,LATIN,ES,ES,0.799182
20287,Catedral de Santa María de Mediavilla,Catedral de Sigueenza,False,6452804,6452828,LATIN,LATIN,ES,ES,0.846504
21966,Punta del Corgo,Punta Gorgo,True,3122791,3122791,LATIN,LATIN,ES,ES,0.915152
22469,Granata,Grana,False,2517115,2517117,LATIN,LATIN,ES,ES,0.942857
23314,Cortijada Los Cazaminches,Los Cazaminches,True,2514773,2514773,LATIN,LATIN,ES,ES,0.777778
23772,Montana de Guamasa,Montana Alta,True,2521797,2521797,LATIN,LATIN,ES,ES,0.850000
24085,Leon,Leono,False,3118531,3118532,LATIN,LATIN,ES,ES,0.960000
25762,Talamanka-de-Kharama,talamanka dy jarama,True,6359364,6359364,LATIN,LATIN,ES,ES,0.812281
26412,Bratuas,Brantoas,True,3127674,3127674,LATIN,LATIN,ES,ES,0.908333
27674,Rio de Revilla de Pedro Fuertes y de Revallos,Río de Revilla de Pedro Fuertes y de Revallos,True,3111931,3111931,LATIN,LATIN,ES,ES,0.959394
28970,A Penha,La Pena,True,3119258,3119258,LATIN,LATIN,ES,ES,0.809524
29714,Chovar,Chóvar,True,2519450,2519450,LATIN,LATIN,ES,ES,0.911111
30854,Llinas,Llinars,True,3118240,3118240,LATIN,LATIN,ES,ES,0.971429
31198,Estribela,Estrivela,True,3122726,3122726,LATIN,LATIN,ES,ES,0.955556
32227,Estacion de El Cuervo,Caserío El Cuervo,False,2518508,2518510,LATIN,LATIN,ES,ES,0.782446
33372,Caserio Miralcampo,Caserío Miralcampo,True,2513829,2513829,LATIN,LATIN,ES,ES,0.954248
33424,Las Curras,Los Curras,True,3118018,3118018,LATIN,LATIN,ES,ES,0.940000
33539,Caserío El Lituero,Caserio El Laminador,False,2518387,2518388,LATIN,LATIN,ES,ES,0.838413
34618,S'Esgleieta,l'Esgleieta,True,2515991,2515991,LATIN,LATIN,ES,ES,0.939394
34842,El Trapiche,Trapiche,True,2510204,2510204,LATIN,LATIN,ES,ES,0.909091
35320,Cortijo El Pozuelo,Caserio El Pozuelo,True,2519833,2519833,LATIN,LATIN,ES,ES,0.760000
35640,Pollença,Pollensa,True,2512432,2512432,LATIN,LATIN,ES,ES,0.950000
36472,Berbedel,Berbegal,True,3128240,3128240,LATIN,LATIN,ES,ES,0.900000
36496,Erretes Tudela / Retes de Tudela,Erretes Tudela,True,3111955,3111955,LATIN,LATIN,ES,ES,0.887500
38912,Rio Aguamia,Rio Guadamia,True,3130893,3130893,LATIN,LATIN,ES,ES,0.891414
39194,Riu Servol,Rio Cervol,True,3109056,3109056,LATIN,LATIN,ES,ES,0.893333
39542,Pereda,Pereda de Sangoñedo,True,3113763,3113763,LATIN,LATIN,ES,ES,0.863158
39568,Noajn,Noáin,True,3115446,3115446,LATIN,LATIN,ES,ES,0.786667
40001,Caserío Aldehuela,Caserio Aldehuela,False,3130466,3130468,LATIN,LATIN,ES,ES,0.976471

In [ ]:
unique_chars = set(df_latin_pairs_filtered.name_1.sum())

In [21]:
unique_chars

{' ',
 '"',
 "'",
 '(',
 ')',
 ',',
 '-',
 '.',
 '/',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '9',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z',
 '_',
 '`',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z',
 '~',
 'Á',
 'Â',
 'Å',
 'Ç',
 'É',
 'Î',
 'Ñ',
 'Ó',
 'Ö',
 'Ø',
 'Ü',
 'ß',
 'à',
 'á',
 'â',
 'ã',
 'ä',
 'å',
 'æ',
 'ç',
 'è',
 'é',
 'ê',
 'ë',
 'í',
 'î',
 'ï',
 'ð',
 'ñ',
 'ò',
 'ó',
 'ô',
 'õ',
 'ö',
 'ø',
 'ù',
 'ú',
 'û',
 'ü',
 'ý',
 'Ā',
 'ā',
 'ă',
 'ą',
 'ć',
 'Č',
 'č',
 'Đ',
 'đ',
 'Ē',
 'ē',
 'ĕ',
 'ė',
 'ě',
 'ğ',
 'ĩ',
 'Ī',
 'ī',
 'ĭ',
 'İ',
 'ı',
 'Ł',
 'ł',
 'ń',
 'ņ',
 'ŋ',
 'Ō',
 'ō',
 'Ŏ',
 'ŏ',
 'ő',
 'œ',
 'ř',
 'Ş',
 'ş',
 'Š',
 'š',
 'Ţ',
 'ţ',
 'ũ',
 'Ū',
 'ū',
 'Ŭ',
 'ŭ',
 'ű',
 'ų',
 'Ż',
 'Ž',
 'ž',
 'Ə',
 'ơ',
 'ư',
 'ǝ',
 'ș',
 'ț',
 'ə',
 'ʹ',
 'ʻ',
 'ʼ',
 'ʾ',
 'ʿ',
 'ˌ',
 '̄',
 '̆',
 '̇',
 '̧',
 '̱',
 '̲',
 'ḍ',
 'Ḏ',
 'ḏ',
 'Ḑ',
 'ḑ',
 'ḥ',
 'Ḩ',
 'ḩ',
 'ṅ',
 'ṉ',
 'ṟ',
 'Ṣ',
 'ṣ',
 'Ṭ',
 'ṭ',
 'ṯ',
 'ẕ',
 'ạ',
 'ả',
 'Ấ',
 'ế',
 'ễ',
 'ọ',
 'ố',
 'ồ',
 'ộ',
 'ờ',
 'ợ',
 'ủ',
 'ỳ',
 '\u200e',
 '‘',
 '’',
 '”'}